### ISSUE TITLE
Missing Constructor: CirclePageIndicator

### ISSUE THREAD

**Issue by sorgesd** [alexrainman/CirclePageIndicator#1]
We've seen a few crash reports with this stack trace. We originally produced this error in the CarouselView package but are reporting it here since it's been moved to it's own package and the constructor is still missing.

> Xamarin caused by: android.runtime.JavaProxyThrowable: System.NotSupportedException: Unable to activate instance of type CarouselView.FormsPlugin.Android.CirclePageIndicator from native handle 0xffa155ec (key_handle 0xfc768d4). ---> System.MissingMethodException: No constructor found for CarouselView.FormsPlugin.Android.CirclePageIndicator::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
>    --- End of inner exception stack trace ---
>   at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00054] in <6beee5bf80a242e4ada717fa35fa1706>:0 
>   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <6beee5bf80a242e4ada717fa35fa1706>:0 
>    --- End of inner exception stack trace ---
>   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017d] in <6beee5bf80a242e4ada717fa35fa1706>:0 
>   at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000b9] in <6beee5bf80a242e4ada717fa35fa1706>:0 
>   at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <6beee5bf80a242e4ada717fa35fa1706>:0 
>   at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <6beee5bf80a242e4ada717fa35fa1706>:0 
>   at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <6beee5bf80a242e4ada717fa35fa1706>:0 
>   at Android.Support.V4.View.ViewPager+IOnPageChangeListenerInvoker.n_OnPageScrollStateChanged_I (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 state) [0x00000] in <fc4222de5c684a9abf7cc4821baac4cd>:0 
>   at (wrapper dynamic-method) System.Object:d2071220-a64f-4023-9e68-b51a7a0bab9d (intptr,intptr,int)
> 	at md5fa3be16b83ce3acd3be83265686c14de.CirclePageIndicator.n_onPageScrollStateChanged(Native Method)
> 	at md5fa3be16b83ce3acd3be83265686c14de.CirclePageIndicator.onPageScrollStateChanged(CirclePageIndicator.java:93)
> 	at android.support.v4.view.ViewPager.dispatchOnScrollStateChanged(ViewPager.java:1984)
> 	at android.support.v4.view.ViewPager.setScrollState(ViewPager.java:497)
> 	at android.support.v4.view.ViewPager$3.run(ViewPager.java:272)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
> 	at android.view.Choreographer.doFrame(Choreographer.java:655)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
> 	at android.os.Handler.handleCallback(Handler.java:790)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:164)
> 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by alexrainman** [comment]
Yeah, i know what is this, will update it.

**Comment by aimore** [comment]
Any news on this?
after updating to XF4 I am getting the same error mentioned above.

**Comment by sorgesd** [comment]
Would love to hear back on this. When I originally reported this issue, it was randomly popping up. After updating to Xamarin.Forms 3.5.0, it occurs every time I pop a modal with a CarouselView.

**Comment by alexrainman** [comment]
Im currently wotking on a new release. Will keep you guys posted.

**Comment by cassionandi** [comment]
> Would love to hear back on this. When I originally reported this issue, it was randomly popping up. After updating to Xamarin.Forms 3.5.0, it occurs every time I pop a modal with a CarouselView.

On the same boat here

**Comment by lewcianci** [comment]
I'm trying to work this out... I think its lacking a constructor that the updated Android.Support library is referencing.  You can see in the source that theres no constructor that takes CarouselView.FormsPlugin.Android.CirclePageIndicator::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership).

**Comment by ramonesteban78** [comment]
Hi @alexrainman, is this issue solved in version 1.0.3?
Thanks in advance

**Comment by alexrainman** [comment]
Yes it is.

**Comment by xamarindevelopervietnam** [comment]
waiting for new release.

**Comment by CarLoOSX** [comment]
Same problem with 5.2.0 in forms 3.6

**Comment by JRC-BitBull** [comment]
Getting this issue after updating to Forms 4.0.0 - using version 5.2.0.

Is a fix for this imminent, or is there a workaround?

![image](https://user-images.githubusercontent.com/7208690/60094454-06d98600-9744-11e9-8601-ea897b545961.png)

**Comment by onurATpiksel** [comment]
same here
xForms 4.0.0.54...
carousel 5.2.0

**Comment by pramodhgeorge2019** [comment]
When I tried to upgrade the xamarin forms version to 4.2(old version was 2.5) keeping the carouselview.formsplugin.Android(version 5.2,nuget installed in android and .net standard projects). I am getting following errors.
Cannot resolve reference: 'Com.ViewPagerIndicator' ,referenced by 'CarouselView.FormsPlugin.Android' Please add a nuget pacakage or assembly reference for 'Com.ViewPagerIndicator' Or remove the reference to 'CarouselView.FormsPlugin.Android' .
We are using xamarin.android.Support libraries of v4,v7 and v13.
